# Clock signal
set_property PACKAGE_PIN W5 [get_ports clk]       
 set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN R2 [get_ports rst]     
        set_property IOSTANDARD LVCMOS33 [get_ports rst]
#seven-segment LED display
        set_property PACKAGE_PIN W7 [get_ports {disp_segments[6]}]                    
            set_property IOSTANDARD LVCMOS33 [get_ports {disp_segments[6]}]
        set_property PACKAGE_PIN W6 [get_ports {disp_segments[5]}]                    
            set_property IOSTANDARD LVCMOS33 [get_ports {disp_segments[5]}]
        set_property PACKAGE_PIN U8 [get_ports {disp_segments[4]}]                    
            set_property IOSTANDARD LVCMOS33 [get_ports {disp_segments[4]}]
        set_property PACKAGE_PIN V8 [get_ports {disp_segments[3]}]                    
            set_property IOSTANDARD LVCMOS33 [get_ports {disp_segments[3]}]
        set_property PACKAGE_PIN U5 [get_ports {disp_segments[2]}]                    
            set_property IOSTANDARD LVCMOS33 [get_ports {disp_segments[2]}]
        set_property PACKAGE_PIN V5 [get_ports {disp_segments[1]}]                    
            set_property IOSTANDARD LVCMOS33 [get_ports {disp_segments[1]}]
        set_property PACKAGE_PIN U7 [get_ports {disp_segments[0]}]                    
            set_property IOSTANDARD LVCMOS33 [get_ports {disp_segments[0]}]
        set_property PACKAGE_PIN U2 [get_ports {disp_select[0]}]                    
            set_property IOSTANDARD LVCMOS33 [get_ports {disp_select[0]}]
        set_property PACKAGE_PIN U4 [get_ports {disp_select[1]}]                    
            set_property IOSTANDARD LVCMOS33 [get_ports {disp_select[1]}]
        set_property PACKAGE_PIN V4 [get_ports {disp_select[2]}]                    
            set_property IOSTANDARD LVCMOS33 [get_ports {disp_select[2]}]
        set_property PACKAGE_PIN W4 [get_ports {disp_select[3]}]                    
            set_property IOSTANDARD LVCMOS33 [get_ports {disp_select[3]}]